### ISSUE TITLE
PrismApplicationBase.Container having difficulty resolving ILogger<T>

### ISSUE THREAD

**Issue by Mardoxx** [dansiegel/Prism.Container.Extensions#100]
This is using `Prism.Unity` and `Prism.Unity.Extensions`

```cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Prism.Ioc;
using Prism.Unity;
using System.Windows;

namespace SampleApp1
{
    public partial class App : PrismApplication
    {
        protected override Window CreateShell() => Container.Resolve<Views.MainWindow>();

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            PrismContainerExtension.Current.RegisterServices(services =>
            {
                services.AddLogging();
            });

            PrismContainerExtension.Current.Resolve<ILogger<App>>(); // works
            Container.Resolve<ILogger<App>>(); // fails
        }
    }
}
```

I'm also having difficulty understanding why we can't do the following:

```cs
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterScoped<MyDependency>();
}
```

.... let me follow up with an answer because I just worked it out

**Comment by Mardoxx** [comment]
So usage is, install `Prism.Unity.Extensions` override `ApplicationBase.CreateContainerExtension()` to return the `IContainerExtension` from `Prism.Unity.Extensions`. Then use extension methods on the instance, not the static ones to register your services in `RegisterTypes(...)`

i.e.

```cs
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterServices(services =>
    {
        services.AddLogging();
    });
}

protected override IContainerExtension CreateContainerExtension() => PrismContainerExtension.Create();
```

**Comment by dansiegel** [comment]
Keep in mind that this does not work out of the box with WPF... you're going to need to do a little bit of wiring up as it requires adding a container adapter and connecting the CommonServiceLocator... both things that will go away once we shift to working on some Prism 8 releases....
