### ISSUE TITLE
Use in wpf raised Exception

### ISSUE THREAD

**Issue by qtbui159** [dansiegel/Prism.Container.Extensions#106]
Use Prism.Wpf(7.2.0.1422) and Prism.Microsoft.DependencyInjection.Extensions(7.2.0.1054)

```
public abstract class PrismApplication : PrismApplicationBase
{
        protected override IContainerExtension CreateContainerExtension()
        {
            return PrismContainerExtension.Current;
        }

        protected override void RegisterFrameworkExceptionTypes()
        {           

          ExceptionExtensions.RegisterFrameworkExceptionType(typeof(ContainerResolutionException));
        }
} 

public partial class App : PrismApplication
{
        protected override Window CreateShell()
        {
            return Container.Resolve<MainWindow>();
        }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
        }
}
``` 

When I run the app, it raise 
```
System.InvalidOperationException: 
“Unable to resolve service for type 'CommonServiceLocator.IServiceLocator' while attempting to activate 'Prism.Regions.RegionBehaviorFactory'.”
```

How can I solve this problem?

**Comment by dansiegel** [comment]
This does not work out of the box for WPF... at least not for 7.2

https://github.com/PrismLibrary/Prism/blob/a2231bee4a5d7cb41eefc384a871831583eb63f9/Source/Wpf/Prism.Unity.Wpf/PrismApplication.cs#L19-L24

As you'll notice the Container specific implementation of PrismApplication registers an Adapter for IServiceProvider and the RegionNavigationContentLoader. You'd need to provide both of these implementations.
