### ISSUE TITLE
integration with Microsoft.Extensions.Http doesn't works

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Container.Extensions#117]
I've added  Microsoft.Extensions.Http to use the goodies of IHttpClientFactory, but when I'm trying to inject HttpClient anywere of the app the DI container raise an exception and does't completed the operation.

Steps to reproduce:

a) Create a clean Xamarin Forms from Prism Template Pack
b) replace Prism.DryIoc.Forms to use container extensions:
   i) Prism.DryIoc.Extensions v7.2.0.1054
   ii) Prism.Forms.Extended v7.2.0.1054
c) Microsoft.Extensions.Http v3.1.5
d) inject HttpClient as dependency to any type and acess this object

**Comment by dansiegel** [comment]
Can you provide a reproduction of the issue.

**Comment by candidodmv** [comment]
Hello @dansiegel follow the link to a reproduction of the issue:

https://github.com/candidodmv/PrismAndContainerExtensions

**Comment by dansiegel** [comment]
You're using Shiny and it appears you're trying to resolve services that were registered with Shiny... in order to have both Prism and Shiny using the same container you need to use Shiny.Prism and use the PrismStartup in lieu of the ShinyStartup

**Comment by candidodmv** [comment]
@dansiegel installed and configured Shiny.Prism in the sample project as you said before, but nothing changed. What I'm missing?

**Comment by jaelys** [comment]
What is the correct use?
I use the following code always wrong
I use Prism.Unity 8.1.97  , Prism.Unity.Extensions 8.0.62
```
protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {            
            containerRegistry.RegisterServices(services =>
            {               
                services.AddHttpClient();
            });
         }
```

error No public constructor is available for type System.IServiceProvider.
