### ISSUE TITLE
Exception on Android in Release configuration

### ISSUE THREAD

**Issue by gmwilhelm** [dansiegel/Prism.Container.Extensions#142]
Hello,

i created a new prism app using the Prism Template Pack.

I removed Prism.Forms and added

- Prism.Dryioc.Extensions v7.2.0.1054
- Shiny.Prism v7.2.0.1054

Now when i run the app in debug configuration, everything works fine.

But in release configuration, the app hangs after the splashscreen and does not navigate to MainPage.

In the device console i get this exception (see the full exception in the log.txt):

> Exception - High: Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'Prism.Navigation.INavigationService', with the service name 'PageNavigationService' ---> System.TypeInitializationException: The type initializer for 'FastExpressionCompiler.LightExpression.ILGeneratorHacks' threw an exception. ---> System.InvalidOperationException: Sequence contains no matching element

I tested this in an emulator (Oreo 8.1, Api 27) and on a real device (Nexus 6P, Android 7.1, Api 25)

What can i do to resolve this?

[log.txt](https://github.com/dansiegel/Prism.Container.Extensions/files/5136155/log.txt)

[PrismTestApp.zip](https://github.com/dansiegel/Prism.Container.Extensions/files/5136109/PrismTestApp.zip)

**Comment by dadhi** [comment]
@dansiegel @gmwilhelm  
Looking into this, thanks for the log

**Comment by dadhi** [comment]
@gmwilhelm @dansiegel 

[DryIoc v4.3.3](https://github.com/dadhi/DryIoc/releases/tag/v4.3.3) is out with the fix.

**Comment by dansiegel** [comment]
@dadhi thanks for looking into the issue and a quick fix!

@gmwilhelm be sure to add DryIoc.dll as a direct PackageReference so you can use the latest build and resolve your issue. I'll be updating Prism.Container.Extensions soon. It's currently unclear whether I'll be doing another service release for 7.2 as I'm currently working on getting out a 8.0 preview

**Comment by gmwilhelm** [comment]
Thank you very much
