### ISSUE TITLE
Object Disposed Errors on IServiceProvider (Prism.Microsoft.DependencyInjection.Extensions) on main branch

### ISSUE THREAD

**Issue by maxpiva** [dansiegel/Prism.Container.Extensions#147]
Going Back and Forward from navigation will trigger the issue. (Relative Navigation)

Removing the disposing of the IServiceProvider in ConcreteAwareServiceScope will fix the issue.

Recreating it does not seems to be a valid approach since you might have singletons already initialized.

**Comment by dansiegel** [comment]
If you'd like to take a crack at it I'm happy to accept a PR

**Comment by dansiegel** [comment]
closed by #148
