### ISSUE TITLE
Register assembly in container 

### ISSUE THREAD

**Issue by SalimiHabib** [dansiegel/Prism.Container.Extensions#150]
how can register all types  in assembly at once ?
my setup is 

```
`    <PackageReference Include="Prism.DryIoc.Extensions" Version="7.2.0.1054" />

    <PackageReference Include="Prism.Forms.Extended" Version="7.2.0.1054" /> 

    <PackageReference Include="Shiny.Prism" Version="7.2.0.1054" />
`
```
Also some types are internal with public constructor in that assembly that need to be registered 

thank you

**Comment by dadhi** [comment]
Just for the reference, in DryIoc you will register the assemblies via `RegisterMany` with the optional argument `nonPublicServiceTypes: true`.

@dansiegel Is it translated to the Prism api?

**Comment by dadhi** [comment]
> var implTypes = typeof(IEdgeProvisioningService).GetAssembly().GetTypes()

Filter your implementation types:

```cs
var implTypes = typeof(IEdgeProvisioningService).GetAssembly().GetTypes().Where(t => t.IsImplementationType());
```

Here is the all the goodies https://www.fuget.org/packages/DryIoc.dll/4.4.1/lib/netstandard2.0/DryIoc.dll/DryIoc/Registrator,  search for `IsImplementationType`
https://www.fuget.org/packages/DryIoc.dll/4.4.1/lib/netstandard2.0/DryIoc.dll/DryIoc/Registrator

**Comment by dansiegel** [comment]
automatic registration of an assembly isn't something I'm going to do for Prism or the Container Extensions here. However this sort of functionality is something that I'm open to duplicating for the Prism.Magician.

That said the RegisterMany in Prism should pull in any interface that is on a given type if you do not specify any service types.

https://github.com/PrismLibrary/Prism/blob/261790736d7f73491d6baffcd35de6afee27f97b/src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs#L152-L161
