### ISSUE TITLE
Please provide a sample WPF application using  Prism.Microsoft.DependencyInjection.Extensions

### ISSUE THREAD

**Issue by DermotMurphy** [dansiegel/Prism.Container.Extensions#157]
I have some .Net Core applications which have dependencies on FluentValidation and Mediatr which have extension methods to register items in the ServiceCollection.

I would like to leverage these extension methods in a WPF application.

A sample WPF Prism Application would help enormously.

**Comment by juner** [comment]
@DermotMurphy 
Is it related to #106 ?

**Comment by DermotMurphy** [comment]
Sorry,

I missed that nugget of information. I shall look forward to Prism * and keep my fingers crossed for WPF support.

Thanks

**Comment by DermotMurphy** [comment]
Hahaha ... **Prism 8** NOT Prism *

**Comment by dansiegel** [comment]
Prism.Wpf & Prism.Uno are virtually identical... this is tested against Prism.Forms and was built originally for Prism.Forms. That said a couple of things to note:

- This is an Open Source project. I have no obligation to anyone to provide samples for their use case.
- The "Extensions" part of the Prism.Container.Extensions were mostly baked into Prism 8 making it mostly obsolete
- The Shiny and IServiceCollection support which is the one thing that this really does, that is not part of Prism 8.. are better handled by the Prism Magician
- Prism.Microsoft.DependencyInjection.Extensions is a mostly experimental container. It's out there, there may be some bugs and things I haven't accounted for. It's really on the community to help support it if people want it.
