### ISSUE TITLE
The type or namespace name 'Preserve' could not be found

### ISSUE THREAD

**Issue by JeremyBP** [dansiegel/Prism.Container.Extensions#163]
Hi Dan,

I'm facing this error while building a newly created blank project with Prism Template Pack and referencing Prism.DryIoc.Extensions v8.0.20-beta from SponsorConnect:

`[MyWindowsUserPath]\.nuget\packages\prism.dryioc.extensions\8.0.20-beta\build\PreserveContainerExtension.cs(4,12,4,20): error CS0246: The type or namespace name 'Preserve' could not be found (are you missing a using directive or an assembly reference?)`

![PreserveError](https://user-images.githubusercontent.com/4272307/99369697-099ac500-28bd-11eb-99c7-527b708e270d.png)

Same error message on both iOS and Android side but no problem with the actual v7.2.0.1054 NuGet version.

Well, I can find a PreserveAttribute.cs file while browsing files from this [v7 tagged commit](https://github.com/dansiegel/Prism.Container.Extensions/tree/40b77f34a006b4ca661a356ec455690dc460e0cf/src/Prism.DryIoc.Extensions), but I can't with the [last version](https://github.com/dansiegel/Prism.Container.Extensions/tree/master/src/Prism.DryIoc.Extensions).

Interesting thing is that older v7 projects build succesfully after v8 update... It started to appear with new blank one.

Am I missing something?

Thanks

**Comment by dansiegel** [comment]
Thanks for the report. Definitely sounds like a bug. You should be able to work around it until I get a fix out by updating the PackageReference to exclude build assets.
