### ISSUE TITLE
System.NotImplementedException: "The method or operation is not implemented." when using the extension library

### ISSUE THREAD

**Issue by Gakki123** [dansiegel/Prism.Container.Extensions#164]
![image](https://user-images.githubusercontent.com/33748042/99872355-3b44c080-2c1c-11eb-8557-c1b643d1039f.png)
I am using the extension library to inject httpapi, but System.NotImplementedException: "The method or operation is not implemented."
![image](https://user-images.githubusercontent.com/33748042/99872453-db024e80-2c1c-11eb-9d2e-b0dccbc0505f.png)

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

内部异常 1:
TypeLoadException: Method 'CreateScope' in type 'Prism.Unity.PrismContainerExtension' from assembly 'Prism.Unity.Extensions, Version=7.2.0.1054, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by dansiegel** [comment]
You need to provide a sample reproduction of the issue you're facing. I'm guessing most likely that the issue is that you're trying to use Prism.Unity.Forms and Prism.Unity.Extensions and not Prism.Forms.Extended which means you never get the container instance that has the extensions implemented.
