### ISSUE TITLE
update shiny and prism cause me error "ValueFactory attempted to access the Value property of this instance"

### ISSUE THREAD

**Issue by isamBr** [dansiegel/Prism.Container.Extensions#213]
Please I need your help
, I got the same issue after me update shiny and prism
Prism.Container.Extensions" Version="8.0.62"
Prism.Core Version="8.1.97"
Prism.DryIoc.Extensions Version="8.0.62"
"Prism.Forms" Version="8.1.97"
Prism.Forms.Extended" Version="8.0.62"
![image](https://user-images.githubusercontent.com/15988391/147388811-ef372d80-7153-427d-8f4b-631786c572f3.png)

![image](https://user-images.githubusercontent.com/15988391/147388780-154d2b5e-5973-4abe-a15d-f189610d3842.png)

**Comment by aritchie** [comment]
Shiny.Prism is no longer used.  You need to move to Shiny.Framework at https://github.com/shinyorg/framework - there are samples of how to use it here: https://samples.shinylib.net

**Comment by isamBr** [comment]
@aritchie    Thanks for response but I wasn't able to run this example, something to do with sponsor connect what I m doing wrong?
![image](https://user-images.githubusercontent.com/15988391/147756534-a730d4b2-0ad2-4b21-921c-b23ce85f512b.png)

**Comment by isamBr** [comment]
![image](https://user-images.githubusercontent.com/15988391/147757780-661b4b50-e1a7-4903-9929-1339a506250f.png)

**Comment by dansiegel** [comment]
@isamBr let's continue this via email. dsiegel @ avantipoint dot com
