### ISSUE TITLE
unable to inject IHttpClientFactory with PrismContainerExtension

### ISSUE THREAD

**Issue by markat1** [dansiegel/Prism.Container.Extensions#214]
I'm pretty new when it comes to using prism.

I want to inject IHttpClientFactory in WPF (I'm using Unity), but the following doesn't work. It wouldn't start WPF interface. It just crashes. 

First I tried injecting IHttpClientFactory  using the regular dependency injection for prism, but without any luck. Then a couple of people on stackoverflow suggested I should try PrismContainerExtension, but that certain didn't work either.

 What am I doing wrong? 

**app.xaml.cs**
```

    protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            PrismContainerExtension.Current.RegisterServices(s =>
            {
                s.AddHttpClient("test.api", c=>
                {
                    c.BaseAddress = new Uri("http://test.com/api");
                });

            });
        }
```

**viewmodel**

```
    public MainWindowViewModel(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

**Comment by sawankumarbundelkhandi** [comment]
I am also getting this error. @markat1 have you found any solution?

**Comment by markat1** [comment]
@[sawankumarbundelkhandi](https://github.com/sawankumarbundelkhandi) . I ended up using         `static readonly HttpClient client = new HttpClient();`

**Comment by sawankumarbundelkhandi** [comment]
Actually, I am able to fix this. Also, I was getting this error in a Xamarin Forms app.

I was missing the assembly part when importing the prism. When I add the assembly=Prism.Forms.Extended in the xmlns:prism namespace everything started working.

Below is what my App.xaml looks like and the injection is working just fine.

```
<?xml version="1.0" encoding="utf-8" ?>
<prism:PrismApplication xmlns="http://xamarin.com/schemas/2014/forms"
                       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                       xmlns:prism="clr-namespace:Prism;assembly=Prism.Forms.Extended"
                       x:Class="xxx.App">
</prism:PrismApplication>
```

**Comment by markat1** [comment]
hmm - can you show me your RegisterTypes and viewmodel? - [sawankumarbundelkhandi](https://github.com/sawankumarbundelkhandi)

**Comment by sawankumarbundelkhandi** [comment]
can you try changing `xmlns:prism="http://prismlibrary.com/"` to  `xmlns:prism="clr-namespace:Prism;assembly=Prism.Forms.Extended"` ?

**Comment by sawankumarbundelkhandi** [comment]
Also, I am not using directly IHttpClientFactory in my viewmodel.   I am using strawberry shake graphql library  which internally is using IHttpClientFactory.

https://chillicream.com/docs/strawberryshake/get-started/xamarin/#step-4-add-a-graphql-client-to-your-project-using-the-cli-tools

**Comment by markat1** [comment]
So i tried the following:

```
<prism:PrismApplication
    x:Class="Test.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="clr-namespace:Test"
    xmlns:prism="clr-namespace:Prism;assembly=Prism.Forms.Extended">
    <Application.Resources>
    </Application.Resources>
</prism:PrismApplication>
```

Unfortunately that [sawankumarbundelkhandi](https://github.com/sawankumarbundelkhandi) didn't work,  I get the following error: 

```
Error_:MC3074	The tag 'PrismApplication' does not exist in XML namespace 'clr-namespace:Prism;assembly=Prism.Forms.Extended'. Line 2 Position 5.		
```

**Comment by dansiegel** [comment]
You were doing a lot wrong if you had to bring in Prism.Forms.Extended... Going back to your initial comment, you should never be referencing the ContainerLocator unless it's in a context where you have absolutely no other way of accessing the container... An example would be a Type Converter or within a custom control that you're going to use in XAML as you cannot inject the container otherwise.

I can pretty much guarantee that you still had a reference to Prism.DryIoc.Forms which tells me that you were never using the Extended version of the container because you didn't wire things up properly. If you had simply referenced Prism.Forms and updated your App to inherit from PrismApplicationBase you would have had to implement the CreateContainerExtension method where you would return the correct container instance.

**Comment by markat1** [comment]
No I wasn't using  Prism.Forms.Extended ;) - that was just a guy here who suggested that.

So perhaps you have an example on how to inject Ihttpclientfactory into viewmodel using unity? I just tried following the guide on the page https://prismplugins.com/ and part of https://prismlibrary.com/docs/wpf/getting-started.html.

I haven't had any luck finding a great source on how to do this.

just any simple sample that uses unity would be great. It just have to show how to inject IHttpClientFactory into a viewmodel. That's it. 

At the moment I use :` static readonly HttpClient client = new HttpClient()`.

**Comment by dansiegel** [comment]
The sample is simple use the right container. If you are not using the right container you will get an error

**Comment by markat1** [comment]
Is there any way I can remove this "issue" ? apparently I can't figure that out either. If can do that I would be pleased ;)
