### ISSUE TITLE
Samples with Shiny

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Container.Extensions#29]
I'm getting some issues to try implment "Prism.DryIoc.Forms.Extended" with Shiny. is it possible to provide some application sample that use these packages ?

Thanks!

**Comment by candidodmv** [comment]
A sample that share the DryIoC container with Shiny. I found some implmentations that use each of yours  own IoC implmentations (DryIoC in one side and Shiny IoC to other), but it's not a good idea to performance.

**Comment by candidodmv** [comment]
Look this:

        ```
protected override IContainerExtension CreateContainerExtension()
        {
            var container = new Container(this.CreateContainerRules());
            ShinyHost.Populate((serviceType, func, lifetime) =>
                container.RegisterDelegate(
                    serviceType,
                    _ => func(),
                    Reuse.Singleton // HACK: I know everything is singleton
                )
            );
            return new DryIocContainerExtension(container);
        }
```
The code snippet above its creating a reference from one container to another.  is it a good idea?

**Comment by dansiegel** [comment]
you just need to use the Startup class provided by the Shiny.Prism package. It takes care of properly creating the Service provider... and short answer is no it is not a good idea to just create one container from the other.

Closing this as I'm not currently planning on adding any sample apps. This should already be taken care of in the ReadMe
