### ISSUE TITLE
Splat updates

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Container.Extensions#33]
Hi @dansiegel as you said before at #32 , there's a commit updating splat to 8.2.4 when this changes will be released? There's prediction? Becuase my project depends of sqlite-net-pcl, Akavache and there's no common Splat version between these. Because of this , I will need left one of these projects but I need of all. Thanks for help!

**Comment by candidodmv** [comment]
This also will solve the error #28

**Comment by dansiegel** [comment]
Issue #31 is preventing me from generating a successful build because of a change in the tooling that is causing projects with Android targets to fail. As soon as I have that issue resolved a new release will go out.

**Comment by dansiegel** [comment]
@candidodmv Issue #31 is fixed now. You can pull the build from MyGet to unblock you

**Comment by candidodmv** [comment]
Thanks @dansiegel , I will check out right now.

**Comment by candidodmv** [comment]
@dansiegel  thanks for enfort to bring updates  but, I decide to left this package, It's idea  is really preaty cool but, there is a lot of gaps when try to integreate with other libraries, differences in deep implementation that raise bugs that requires much time to track. Thanks again
