### ISSUE TITLE
Prism.Container.Extensions doesn't run side by side with Akavache on Android

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Container.Extensions#39]
If you try initialize the container onCreate of MainApplication on Android and follows try Initalize the Akavache will gets an error. I've investigating and seen that because their shared library Splat, both use its internally and it seems that one is cleaning the dependencies registered by other.

I have a code sample here:

https://github.com/candidodmv/AcrDialogsPrismModule/tree/containerExtensionWithAkavache

**Comment by aritchie** [comment]
Acr.UserDialogs hasn't had Splat as a dependency since .net standard 2 was released.  I'd suggest looking deeper into the error message.

**Comment by candidodmv** [comment]
@aritchie the source of the issue is try to run Akavache + Prism.Container.Extensions. The sample project name is just a reusing existing code. I suggest that Prism.Container.Extensions does the same as Acr.UserDialogs, remove the dependency of Splat.

**Comment by dansiegel** [comment]
Closing as we will be dropping support for Splat in the next release see issue #43
