### ISSUE TITLE
Drop support for Splat

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism.Container.Extensions#43]
Splat seems to be more trouble than it's worth. Since nobody is really using this this will reduce dependencies for the bulk of users.

**Comment by JeremyBP** [comment]
The same pb with ReactiveUI 10+ wich ref Splat > 9.0.2. There's a method resolution exception due to splat version conflict.
Actually trying to reproduce the Allan's [Stream-Todo](https://github.com/aritchie/Stream-Todo) sample project but with your libs and get stuck by this issue
