### ISSUE TITLE
Question: Shiny.Prism and Xamarin.Forms UWP 

### ISSUE THREAD

**Issue by ncg81** [dansiegel/Prism.Container.Extensions#50]
Hi @dansiegel,

Thank you for publishing this excellent library!

I have a **Xamarin.Forms** (.NET Standard) project (**Android**, **iOS** & **UWP**) and I've been experimenting by replacing the original Prism packages with these:

> Prism.DryIoc.Forms.Extended (7.2.0.661)
> Shiny.Prism (7.2.0.661-pre)

My `App : PrismApplication` is therefore using the `PrismApplication` from `Prism.DryIoc.Forms.Extended` as per docs.

I noticed that on **Android** (and most likely on **iOS** - haven't tested it yet) the following code works out of the box:

```
    public class AppStartup : PrismStartup
    {
        protected override void ConfigureServices(IServiceCollection services)
        {
            services.UseNavigationDelegate();
        }
    }
```

However, the same on **UWP** results in:

`System.NotImplementedException: 'You must implement PrismStartup.CreateContainerExtension() or Supply the PrismStartup with an instance of IContainerExtension'`.

Modifying the above `AppStartup` to

```
    public class AppStartup : PrismStartup
    {
        protected override void ConfigureServices(IServiceCollection services)
        {
            services.UseNavigationDelegate();
        }

        protected override IContainerExtension CreateContainerExtension() => PrismContainerExtension.Current;
    }

```
works just fine.

I used the [Shiny docs](https://shinydocs.azurewebsites.net/docs/gettingstarted) as a reference for wiring **Shiny.Prism** into my **Android**, **iOS** & **UWP** projects.

I was expecting the same behavior across all 3 project types as the documentation [mentions](https://github.com/dansiegel/Prism.Container.Extensions#shinyprism)  :

> With your App using the PrismApplication from Prism.DryIoc.Forms.Extended you now only need to reference the PrismStartup as the base class for your Startup class

What am I missing? What is the proper way to wire **Shiny.Prism** into a Xamarin.Forms **UWP** project since apparently it is not as automatic as the **Android** & **iOS** counterparts ?

Regards.

**Comment by dansiegel** [comment]
I would expect all 3 platforms to throw the following:

> System.NotImplementedException: 'You must implement PrismStartup.CreateContainerExtension() or Supply the PrismStartup with an instance of IContainerExtension'

When your Startup implementation looks like:

```cs
public class AppStartup : PrismStartup
{
    protected override void ConfigureServices(IServiceCollection services)
    {
          services.UseNavigationDelegate();
    }
}
```

And when your ShinyHost Init looks something like:

```cs
SampleShinyHost.Init(new AppStartup());
```

The problem with the above code is that when CreateServiceProvider is called by Shiny, the base PrismStartup has no reference to an IContainerExtension instance. To fix this you should consider one of following:

```cs
// Method 1
public class AppStartup : PrismStartup
{
    public AppStartup()
        : base(PrismContainerExtension.Current)
    {
    }
}

// Method 2
public class AppStartup : PrismStartup
{
    protected override IContainerExtension CreateContainerExtension() => 
        PrismContainerExtension.Current;
}

// Method 3
SampleShinyHost.Init(new AppStartup().WithContainer(PrismContainerExtension.Current));
```

If you are truly seeing different behavior than this please submit a sample application that demonstrates the issue so that I can look into it further.

**Comment by ncg81** [comment]
> I would expect all 3 platforms to throw the following:
> 
> > System.NotImplementedException: 'You must implement PrismStartup.CreateContainerExtension() or Supply the PrismStartup with an instance of IContainerExtension'
> 
> When your Startup implementation looks like:
> 
> ```cs
> public class AppStartup : PrismStartup
> {
>     protected override void ConfigureServices(IServiceCollection services)
>     {
>           services.UseNavigationDelegate();
>     }
> }
> ```
> And when your ShinyHost Init looks something like:
> 
> ```cs
> SampleShinyHost.Init(new AppStartup());
> ```
> 

Then the [Shiny.Prism](https://github.com/dansiegel/Prism.Container.Extensions#shinyprism) section in the repo's **Readme.md** is incorrect @dansiegel , because the code posted there matches mine. I think what happens is that the example code was taken from Shiny docs some time ago, but Shiny has no awareness of the wiring necessary for **Prism.Container.Extensions**. Glancing at those samples leads one to believe that more stuff is automatically handled by **Prism.Container.Extensions** than it actually is. 

Could you please update the code samples and add an entry for **UWP**  wiring like **Android** and **iOS** have? 

Shiny's [docs](https://shinydocs.azurewebsites.net/docs/gettingstarted) cover **Android**, **iOS** and **UWP**. I think it would be nice to align them and slay any confusion that might arise.

Regards.
