### ISSUE TITLE
Can we support Standard 2.0 for Shiny.Prism

### ISSUE THREAD

**Issue by nick5454** [dansiegel/Prism.Container.Extensions#64]
Right now UWP does not support Standard 2.1.
Shiny supports Standard 2.0 =>
SQLite support for Standard 2.1 does not exist yet for the support packages
Ie.., Have to use EF Core SQLite 2.2.6 because supporting SQLite packages are broken for SQLite 2.0

We use UWP to view local data, but if we go to 2.1 we can't build UWP

So based on these issue, can we get a build for Standard 2.0 until Erick and others have caught up?

**Comment by nick5454** [comment]
I also tried to bring my Prism up to Standard 2.1 and it wrecked all kinds of Havoc

**Comment by nick5454** [comment]
If I created the issue in the wrong place, this in for Shiny.Prism

**Comment by dansiegel** [comment]
yes... absolutely... I actually was able to roll back the changes. It should be in the next CI build
