### ISSUE TITLE
iOS App Crashes on Launch

### ISSUE THREAD

**Issue by ITninja04** [dansiegel/Prism.Container.Extensions#65]
Good morning!

I've been working for the past 4 days to try and figure this one out on my own and keep coming up empty.

I have a Xamarin Forms App:
Xamarin.Forms v4.3.0.991211
Prism.DryIoc.Forms.Extended 7.2.0.702
(can provide more detail here if needed)

App works on Android just fine, iOS it crashes regardless of iPhone/iPad model and iOS version.

The info below is what is spit out by VS (also occurs on my mac and pc).

I've removed all packages, cleaned, cleared nuget cache and validated every line of XAML by hand and with the help of MFractor.

I'm really in a bind here, and feel like it's something really small, but I cannot figure it out.

2019-12-03 06:24:14.258833-0600 AtchleyAirApp.iOS[65070:2102053] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UIApplication.m:3861
2019-12-03 06:24:14.394366-0600 AtchleyAirApp.iOS[65070:2102053] Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch
Native stack trace:
	0   CoreFoundation                      0x00000001152198db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000116125ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115219662 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000110e2f76b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x000000011f384a45 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2992
	5   UIKitCore                           0x000000011ebc8a4e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	6   UIKitCore                           0x000000011ebd1346 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	7   UIKitCore                           0x000000011ebc8664 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	8   UIKitCore                           0x000000011ebc8fc0 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	9   UIKitCore                           0x000000011ebc7332 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	10  UIKitCore                           0x000000011ebc6fe9 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	11  UIKitCore                           0x000000011ebcbd2e __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	12  UIKitCore                           0x000000011ebcc988 _performActionsWithDelayForTransitionContext + 100
	13  UIKitCore                           0x000000011ebcba95 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	14  UIKitCore                           0x000000011ebd0a48 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	15  UIKitCore                           0x000000011f382dc8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	16  UIKitCore                           0x000000011ef3a02f -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	17  FrontBoardServices                  0x000000011e09ad25 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	18  FrontBoardServices                  0x000000011e0a4ad6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	19  FrontBoardServices                  0x000000011e0a4300 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	20  libdispatch.dylib                   0x00000001174dbd02 _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00000001174ded41 _dispatch_block_invoke_direct + 295
	22  FrontBoardServices                  0x000000011e0d60da __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	23  FrontBoardServices                  0x000000011e0d5d92 -[FBSSerialQueue _performNext] + 451
	24  FrontBoardServices                  0x000000011e0d6327 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	25  CoreFoundation                      0x0000000115180db1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	26  CoreFoundation                      0x0000000115180633 __CFRunLoopDoSources0 + 243
	27  CoreFoundation                      0x000000011517acef __CFRunLoopRun + 1231
	28  CoreFoundation                      0x000000011517a4d2 CFRunLoopRunSpecific + 626
	29  GraphicsServices                    0x0000000117f062fe GSEventRunModal + 65
2019-12-03 06:24:14.395040-0600 AtchleyAirApp.iOS[65070:2102053] 
	30  UIKitCore                           0x000000011f385fc2 UIApplicationMain + 140
	31  ???                                 0x000000013ae1aa22 0x0 + 5282834978
	32  ???                                 0x000000013a9ced93 0x0 + 5278330259
	33  ???                                 0x00000001395286fb 0x0 + 5256677115
	34  ???                                 0x00000001395289c9 0x0 + 5256677833
	35  AtchleyAirApp.iOS                   0x0000000107ca8f75 mono_jit_runtime_invoke + 1589
	36  AtchleyAirApp.iOS                   0x0000000107dd5287 mono_runtime_invoke_checked + 135
	37  AtchleyAirApp.iOS                   0x0000000107ddb70c mono_runtime_exec_main_checked + 108
	38  AtchleyAirApp.iOS                   0x0000000107c08a42 mono_jit_exec + 370
	39  AtchleyAirApp.iOS                   0x0000000107f066ee xamarin_main + 2702
	40  AtchleyAirApp.iOS                   0x0000000107bc34c7 main + 71
	41  libdyld.dylib                       0x0000000117549541 start + 1
	42  ???                                 0x0000000000000003 0x0 + 3

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:406 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:128 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at AtchleyAirApp.iOS.Application.Main (System.String[] args) [0x00002] in /Users/altiview/Projects/AtchleyAir/AtchleyAirV2/AtchleyAirApp/AtchleyAirApp.iOS/Main.cs:19 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at AtchleyAirApp.iOS.Application.Main (System.String[] args) [0x00002] in /Users/altiview/Projects/AtchleyAir/AtchleyAirV2/AtchleyAirApp/AtchleyAirApp.iOS/Main.cs:19 	0   CoreFoundation                      0x00000001152198db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000116125ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115219662 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000110e2f76b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x000000011f384a45 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2992
	5   UIKitCore                           0x000000011ebc8a4e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	6   UIKitCore                           0x000000011ebd1346 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	7   UIKitCore                           0x000000011ebc8664 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
2019-12-03 06:24:14.395422-0600 AtchleyAirApp.iOS[65070:2102053] 
	8   UIKitCore                           0x000000011ebc8fc0 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	9   UIKitCore                           0x000000011ebc7332 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	10  UIKitCore                           0x000000011ebc6fe9 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	11  UIKitCore                           0x000000011ebcbd2e __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	12  UIKitCore                           0x000000011ebcc988 _performActionsWithDelayForTransitionContext + 100
	13  UIKitCore                           0x000000011ebcba95 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	14  UIKitCore                           0x000000011ebd0a48 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	15  UIKitCore                           0x000000011f382dc8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	16  UIKitCore                           0x000000011ef3a02f -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	17  FrontBoardServices                  0x000000011e09ad25 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	18  FrontBoardServices                  0x000000011e0a4ad6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	19  FrontBoardServices                  0x000000011e0a4300 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	20  libdispatch.dylib                   0x00000001174dbd02 _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00000001174ded41 _dispatch_block_invoke_direct + 295
	22  FrontBoardServices                  0x000000011e0d60da __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	23  FrontBoardServices                  0x000000011e0d5d92 -[FBSSerialQueue _performNext] + 451
	24  FrontBoardServices                  0x000000011e0d6327 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	25  CoreFoundation                      0x0000000115180db1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	26  CoreFoundation                      0x0000000115180633 __CFRunLoopDoSources0 + 243
	27  CoreFoundation                      0x000000011517acef __CFRunLoopRun + 1231
	28  CoreFoundation                      0x000000011517a4d2 CFRunLoopRunSpecific + 626
	29  GraphicsServices                    0x0000000117f062fe GSEventRunModal + 65
	30  UIKitCore                           0x000000011f385fc2 UIApplicationMain + 140
	31  ???                                 0x000000013ae1aa22 0x0 + 5282834978
	32  ???                                 0x000000013a9ced93 0x0 + 5278330259
	33  ???                                 0x00000001395286fb 0x0 + 5256677115
	34  ???                                 0x00000001395289c9 0x0 + 5256677833
	35  AtchleyAirApp.iOS                   0x0000000107ca8f75 mono_jit_runtime_invoke + 1589
	36  AtchleyAirApp.iOS                   0x0000000107dd5287 mono_runtime_invoke_checked + 135
	37  AtchleyAirApp.iOS                   0x0000000107ddb70c mono_runtime_exec_main_checked + 108
	38  AtchleyAirApp.iOS                   0x0000000107c08a42 mono_jit_exec + 370
	39  AtchleyAirApp.iOS                   0x0000000107f066ee xamarin_main + 2702
	40  AtchleyAirApp.iOS                   0x0000000107bc34c7 main + 71
	41  libdyld.dylib                       0x0000000117549541 start + 1
	42  ???                                 0x0000000000000003 0x0 + 3
2019-12-03 06:24:14.395664-0600 AtchleyAirApp.iOS[65070:2102053]

**Comment by dansiegel** [comment]
you're dumping a crash log that doesn't really give anyone any relevant information. In any case your issue isn't the Container Extensions but in your code. If you're not just plain throwing an exception then this tells me there is an exception in your Navigation that you aren't inspecting.

```cs
var result = await NavigationService.NavigateAsync("SomePage");
if (!result.Success)
{
    Console.WriteLine(result.Exception);
    Debugger.Break();
}
```
