### ISSUE TITLE
Missing IServiceScopeFactory in Container registry

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Container.Extensions#80]
I'm facing the following issue:

`DryIoc.ContainerException: Unable to resolve Microsoft.Extensions.DependencyInjection.IServiceScopeFactory as parameter "scopeFactory" IsSingletonOrDependencyOfSingleton`

and looking in the original DryIoc provider implementation there is a resgistration of this type, as follows in the following code:

https://github.com/dadhi/DryIoc/blob/4da18a358b7f7471d1455b231af11c7912f4969c/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L43

with the follwing implemenation,

https://github.com/dadhi/DryIoc/blob/4da18a358b7f7471d1455b231af11c7912f4969c/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs#L222

Maybe, it's just implement `IServiceScopeFactory ` in `PrismContainerExtension ` provider and register to container, something like in these lines:

https://github.com/dansiegel/Prism.Container.Extensions/blob/9e4ecba9c997a32fb17b6106d876ef359b2b899c/src/Prism.DryIoc.Extensions/PrismContainerExtension.cs#L83

Ps. I did what I described above (copy the original code and register to container) and the error has gone. 

Thanks.

**Comment by dansiegel** [comment]
I don't recall Prism.Container.Extensions using this... can you provide some clarity around how you're trying to use this.... and why you're trying to do whatever you're trying to do

**Comment by candidodmv** [comment]
I'm using IHttpClientFactory from nuget package `Microsoft.Extensions.Http` and their integrated components such as `Microsoft.Extensions.Http.Polly` all of these depends on `IServiceScopeFactory `

**Comment by dansiegel** [comment]
sorry it's taken a while for me to get back to this. it looks like the tests I had around this stopped just short at actually resolving the IHttpClientFactory... hoping to have a fix for this out today

**Comment by louisoftokyo** [comment]
@candidodmv Did the above merge fix this issue for you? I'm on the latest version and having the exact issue you describe here.

**Comment by candidodmv** [comment]
yes, It solved. Ensure that you are you are using the right version of DryIoC, cause this is the source of the problem. Also check out to clean and rebuild your solution.

**Comment by shuebner** [comment]
If anyone with problems resolving `IServiceScopeFactory` finds this issue like I did, try this (taken from [this comment](https://github.com/dansiegel/Prism.Container.Extensions/issues/180#issuecomment-946113915)):

```csharp
public partial class App
{
    protected override void OnStartup(StartupEventArgs e)
    {
        Prism.DryIoc.PrismContainerExtension.Init();
        base.OnStartup(e);
        // etc
    }

    // etc
}
```

Versions:
* Prism.Wpf 8.1.97
* Prism.DryIoc 8.1.97
* Prism.Container.Extensions 8.0.62
* Prism.DryIoc.Extensions 8.0.62

**Comment by RomaRudyak** [comment]
I have faced this issue too.
Here is my setup:
* Shiny.Framework 2.2.1
* Prism.DryIoc.Forms 8.1.97
* DryIoc.Microsoft.DependencyInjection 5.1.0

I managed to resolve issue by using `WithDependencyInjectionAdapter`.

```csharp
    public override IServiceProvider CreateServiceProvider(IServiceCollection services)
    {
        ContainerLocator.SetContainerExtension(() => 
            new DryIocContainerExtension(
                new Container(DryIocContainerExtension.DefaultRules)
                    .WithDependencyInjectionAdapter(services)));

        IContainer container = ContainerLocator.Container.GetContainer();
        container.Populate(services);
        return container.GetServiceProvider();
    }
```

**Comment by sawankumarbundelkhandi** [comment]
> DryIoC

@candidodmv 

Have you manually installed any version of DryIOC to make it work? I am not able to get it to work.

I am currently using these packages

    <PackageReference Include="Prism.DryIoc.Extensions" Version="8.0.62" />
    <PackageReference Include="Prism.Forms.Extended" Version="8.0.62" />
    <PackageReference Include="Prism.DryIoc.Forms" Version="8.1.97" />

**Comment by candidodmv** [comment]
@sawankumarbundelkhandi I don´t remember which version I´ve installed on that moment, but I suggest you see in the plugins history a release version that maches with the time of comment, and you can try one or two before.

I hope this helps you.

**Comment by sawankumarbundelkhandi** [comment]
@candidodmv thanks for the help. I have figured out the mistake I did and it's fixed.

**Comment by meopoc** [comment]
@sawankumarbundelkhandi  Any chance you can share your fix? Same issue.
